### PR TITLE
Feature/56 dark

### LINKED ISSUE #56: Add dark mode to backend
Note: pull build-scripts repo to latest master compile admin-dark.css

Potential improvement suggested by Johan - Slack 3rd December 2019:
* https://blog.arnellebalane.com/using-the-ambient-light-sensor-api-to-add-brightness-sensitive-dark-mode-to-my-website-82223e754630

### PR DESCRIPTION
**Pull request by yiendos**
This PR closes #56 

## Testing instructions
1. check out this issue/PR locally
2. Be sure to have pulled the latest master for `build-scripts` too:
https://github.com/joomlatools/build-scripts
3. Create a new wordpress site via folioshell and symlink folio-docman 
4. Open up your settings > general options (cmd + space "settings")
5. Switch from dark mode to light mode 

Have a good play about, does any of the html dom/ ui seem off? Anything that doesn't look good under dark mode, or conversly under light mode?

### CODE REVIEW

**Comment by yiendos** [comment]
@jebbdomingo I know you are a big fan of darkmode, so I thought you might like to try this out for foliokit, dark mode easter egg

**Comment by yiendos** [comment]
## Note to developers 

We still have some issues with the uploader.scss as this is pretty much a standalone set of styles. 

And this is really small, but the advanced permissions modal stubbornly refuses to allow us to style span labels such as `Administrator` 

Screenshot 2019-11-09 at 11 52 56

**Comment by yiendos** [comment]
Hi @ercanozkaya we discussed the possibility of harmonising the css files a little further, particularly the uploader.scss:
https://github.com/foliolabs/foliokit/blob/master/code/component/files/resources/assets/scss/uploader.scss

Screenshot 2019-11-26 at 11 19 49

Could you take a look at this and see if our admin.css/ admin-dark.css can be extended to included uploader.scss styles?

**Comment by ercanozkaya** [comment]
@yiendos What do you think of first replacing variables in uploader.scss with the corresponding colors in _variables.scss and then in the second step compiling an uploader-dark.css file?

**Comment by yiendos** [comment]
@ercanozkaya doh! of course that would be the ideal way of handling this!

**Comment by ercanozkaya** [comment]
@yiendos Just did a preliminary merge to bring some CSS fixes into master. You can keep the work on the branch

**Pull request merged**
